CREATE TABLE sys_physical_hba
(
    ID BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    HBA_ID VARCHAR(50),
    NAME VARCHAR(255),
    WWN VARCHAR(255),
    HOST_UUID VARCHAR(50)
);

CREATE TABLE sys_physical_host
(
    ID BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    UUID VARCHAR(50),
    NAME VARCHAR(255),
    IP VARCHAR(50),
    UPDATETIME DATETIME,
    BUS_ID BIGINT,
    REMARK VARCHAR(100),
    MODEL_ID BIGINT,
    DEVICE_TYPE INT
);

CREATE TABLE sys_relation_host
(
    UUID VARCHAR(50),
    IP VARCHAR(50),
    VALUE LONGTEXT,
    SWITCH LONGTEXT,
    STORAGE LONGTEXT,
    HOST LONGTEXT
);

CREATE TABLE sys_relation_storage
(
    UUID VARCHAR(50),
    IP VARCHAR(50),
    VALUE LONGTEXT,
    SWITCH LONGTEXT,
    STORAGE LONGTEXT,
    HOST LONGTEXT
);

CREATE TABLE sys_relation_switch
(
    UUID VARCHAR(50),
    IP VARCHAR(50),
    VALUE LONGTEXT,
    SWITCH LONGTEXT,
    STORAGE LONGTEXT,
    HOST LONGTEXT
);

CREATE TABLE sys_tableinfo_host
(
    UUID VARCHAR(50),
    IP VARCHAR(50),
    VALUE LONGTEXT
);

CREATE TABLE sys_tableinfo_storage
(
    UUID VARCHAR(50),
    IP VARCHAR(50),
    VALUE LONGTEXT
);

CREATE TABLE sys_tableinfo_switch
(
    UUID VARCHAR(50),
    IP VARCHAR(50),
    VALUE LONGTEXT
);

